### ISSUE TITLE
non posso fare nulla :(

### ISSUE THREAD

**Issue by marte-git** [jacopoColozzi/esercizio-bridge-php#1]
avrei commentato il codice ma penso di non avere i diritti per farlo ...
COmunque, non posso controllare oggi quel che avete inviato; lo faro' nel fine settimana.
Il purale di frutto e' "i frutti", oppure, se volete essere blase' e un po' antichi, "le frutta"

**Comment by jacopoColozzi** [comment]
Io l’ho invitata a collaborare al repository e nella sezione dedicata alla gestione degli accessi mi dice “pending invite”.

**Comment by marte-git** [comment]
sorry ma non ho questo invito ...
penso sia una questione di permessi accordati ai collaboratori

comunque logout offre di tornare al sistema ma il link corrispondente manca.
In realta' vi suggerirei di mettere un redirect alla pagina di login, in modo che dopo il logout si torni automaticamnete li'.
